version: '3.8'

networks:
  todo-network:
    driver: bridge

services:
  todo-db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo
    networks:
      - todo-network