version: '3.8'

services:
  todo-api:
    build:
      context: todo-api
      dockerfile: Dockerfile.layered
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://todo-db:5432/todo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "18080:8080"
    networks:
      - todo-network
    restart: always
    depends_on:
      - todo-db

  todo-ui:
    container_name: todo-ui
    build:
      context: todo-ui
      dockerfile: Dockerfile
    ports:
      - "13000:3000"
    environment:
      SERVER_SIDE_API_BASE_URL: http://todo-api:8080
      CLIENT_SIDE_API_BASE_URL: http://localhost:18080
    networks:
      - todo-network
    depends_on:
      - todo-api