apiVersion: v1
kind: Service
metadata:
  name: todo-api-svc
  namespace: springboot-kubernetes
spec:
  type: NodePort
  selector:
    app: todo-api-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  namespace: springboot-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api-pod
  template:
    metadata:
      labels:
        app: todo-api-pod
    spec:
      containers:
        - name: todo
          image: harrishjoshi/todo-api
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: postgres_host
                  name: todo-configmap
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: postgres_port
                  name: todo-configmap
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: postgres_dbname
                  name: todo-configmap
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: postgres_username
                  name: todo-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres_password
                  name: todo-secret