name: Build TODO UI

on:
  push:
    paths:
      - "todo-ui/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "todo-ui/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-todo-ui:
    name: Build todo-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo-ui
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: todo-ui/yarn.lock
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
      
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-ui .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-ui