name: Build TODO API

on:
  push:
    branches: [ "**" ]

jobs:
  build-todo-api:
    name: Build todo-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo-api
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/todo-api
        run: |
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=$IMAGE_NAME
          docker push $IMAGE_NAME